const DAILY_HOROSCOPE_DATA = [
    {
        "name": "Aries",
        "horoscope": "Engaging in fitness and weight loss routines will help you achieve a better physical form. Certain significant tasks may come to a standstill due to a difficult financial situation. Be self-reliant and make your own decisions when it comes to new investments. Don't be discouraged by setbacks — failures are a natural part of life and hold their own kind of beauty. You will become part of something significant that will earn you appreciation and rewards. It's perfectly fine to converse with acquaintances, but revealing your deepest secrets to people whose intentions you don't know is simply a waste of your time and trust. Your health may be affected by the stress your spouse causes you.\n\nThings continue to flow well both personally and professionally, Aries. You're feeling strong and full of vitality, though you might notice that your thoughts are a bit scattered today. Your mind may lack its usual sharpness, and distractions could come easily. This is not an ideal day to launch new projects. Instead, focus on completing unfinished work and wrapping up pending matters to make the most of this day."
    },
    {
        "name": "Taurus",
        "horoscope": "Certain unavoidable situations may cause you some discomfort and unease. However, you must strive to maintain your composure and avoid reacting impulsively to the circumstances. Only thoughtful investments will yield returns — so be very deliberate about where you place your hard-earned money. You might also enjoy carving out time for your hobbies and lending a hand to family members. A romantic involvement will add a delightful spark to your happiness. Business professionals under this sign may be required to undertake an unwanted work-related journey, which could weigh heavily on your mind. Working individuals should steer clear of workplace gossip. Elders of this zodiac sign may choose to reconnect with old friends during their leisure time today. Your partner may do something unexpectedly wonderful that will leave a truly lasting impression.\n\nThe high from your recent achievements might have you tempted to splurge on luxury items that previously seemed impractical, Taurus. This is perfectly fine as long as you exercise discernment and resist impulsive purchases. Similarly, this is not the right time to overindulge in food or drink. By all means, celebrate your wins — but let your good judgment lead the way."
    },
    {
        "name": "Gemini",
        "horoscope": "Children may not behave the way you'd like, which could leave you feeling frazzled and frustrated. You must rein in your temper, as unrestrained anger tends to harm everyone involved — especially the person expressing it — by draining energy and clouding judgment. It only makes situations harder to resolve. Be mindful of your tendency to live in the moment and overspend on leisure and entertainment. Friends will lift your spirits as they organize something fun and exciting for the evening. Romance doesn't appear to be on the cards today. However, any additional knowledge you gain today will give you a distinct advantage when engaging with your peers. You need to step out and connect with people in influential circles. You may witness a tough and assertive side of your spouse today, which might leave you feeling somewhat unsettled.\n\nNot just your own achievements, but also the successes of those in your household could have you riding an emotional high today, Gemini. Your mind is likely to be buzzing with ideas about future possibilities, some of which may not be entirely realistic. Nevertheless, allow yourself a few moments of imaginative thinking. Tomorrow, you'll return to a more grounded perspective and be able to assess things with clearer, more practical eyes."
    },
    {
        "name": "Cancer",
        "horoscope": "You will find relief from the tensions and hardships that have been weighing on you for quite some time. Now is the right moment to make meaningful lifestyle changes that will keep such stress at bay permanently. Today, you may find yourself in a disagreement with someone close to you that could escalate into a legal matter, resulting in the draining of your hard-earned savings. This is a favorable time for entering into a matrimonial alliance. The intoxication of love today will beautifully blur the lines between your dreams and reality. If you've been trying to connect with a particular colleague for a while, today may finally bring that opportunity. When you realize there isn't enough time to spend with your loved ones, it tends to weigh on your heart — and that familiar feeling may resurface today. Today, your spouse will make you feel as though you are the most important person in their world.\n\nToday could turn out to be one of the busiest you've had in quite a while, Cancer. The promise of continued success may have you spending a great deal of time on phone calls, sending messages or emails, or making several quick trips within your community. You may not be able to reach everyone you intended to contact, however. Don't let that discourage you — stay persistent and you will get through to them in time."
    },
    {
        "name": "Leo",
        "horoscope": "You need to keep your emotions in check today. A debtor may credit your account without any prior warning, which could come as a pleasant and welcome surprise. Family members will hold a very special place in your heart today. Your beloved will be thinking of you throughout the day. Plan a surprise and turn it into one of the most beautiful memories of your life together. This is an excellent day for negotiating with new clients. During your free time today, you will finally get around to tasks you had long planned but never found the opportunity to carry out. Something that arrives in the morning today could set a wonderfully positive tone for the rest of your day.\n\nBusiness and financial victories are filling you with joy and a deep sense of satisfaction, Leo. You're also eagerly looking toward future progress. The downside of this period, however, is that certain untrustworthy individuals may try to ride your wave of success for their own gain. Some might even approach you seeking financial assistance. Be cautious about who you choose to help. Not everyone will be honest with you — so don't be swayed by emotionally charged stories designed to manipulate your generosity."
    },
    {
        "name": "Virgo",
        "horoscope": "A persistent health issue could be the root cause of unhappiness in your life. You need to address it as soon as possible in order to restore harmony and joy within the family. An unexpected source may bring you a financial windfall today, helping to ease several ongoing monetary concerns. If you're thinking of hosting a gathering, invite your closest friends — there will be plenty of people to cheer you on and make it a memorable occasion. Your love life has something truly wonderful in store for you today. This is also a great time to express yourself creatively and take on projects that allow your imaginative side to flourish. Today, you may find that spending the entire day curled up alone in a room with a good book is your perfect idea of a fulfilling day.\n\nAs your professional aspirations continue to take shape, Virgo, you may discover that there's a flip side to this progress. For one, new responsibilities may make you question whether you're truly capable of meeting them. Additionally, you might find yourself unexpectedly drawn into the uncomfortable world of office politics. Don't allow these concerns to dampen your enthusiasm. You have all the capability needed to handle the former, and all the wisdom required to sidestep the latter. Keep moving forward and upward."
    },
    {
        "name": "Libra",
        "horoscope": "Today you will be bursting with energy — whatever you set your hands to, you will accomplish in nearly half the usual time. You are likely to earn well today, but be mindful not to let that money slip away carelessly through your fingers. An important development on your personal front will bring immense joy and celebration to both you and your entire family. Romance, however, seems to be struggling today, and even your most heartfelt gifts or gestures may not work their usual charm. The changes taking place at your workplace will ultimately work in your favor. A family member may insist on spending some quality time with you today, and while you'll agree, it may end up being more time-consuming than anticipated. You may feel a little disheartened today upon discovering a small but nagging lie told by your spouse.\n\nRecent breakthroughs on your spiritual journey may leave you feeling both exhilarated and strangely unsettled at the same time. Your intuitive, sensitive side recognizes this as a meaningful step forward on your path, while your rational mind may cast doubt on the validity of what you've experienced. Take comfort in the understanding that reality itself is a relative concept, Libra. What you're sensing and feeling is real and valid for you. Hold onto that truth and continue moving ahead with confidence."
    },
    {
        "name": "Scorpio",
        "horoscope": "There are strong indications of recovery from a physical ailment, which will enable you to once again take part in sports and competitive activities. Today, with the support of a trusted friend, some business-minded individuals are likely to experience meaningful financial gains. This additional income can help resolve many of the challenges you've been facing. Avoid allowing relatives or friends to take over the management of your finances, as this could quickly result in exceeding your budget. Today will reveal to you just how deeply and genuinely your partner truly loves you. Those preparing for competitive examinations must stay calm and composed — do not let exam anxiety get the better of you. Your dedicated efforts will certainly bear positive fruit. An unexpected visit from a distant relative may take up a significant portion of your time today. After numerous highs and lows in your married life, today stands out as a golden day to truly cherish and celebrate your love for each other.\n\nMany of your personal ambitions have either already been fulfilled or are steadily on the path to realization, Scorpio. This has you feeling genuinely energized and elated. However, those around you may begin holding out their hands. You could be approached with requests to donate to charitable causes or to extend personal loans to people you barely know. While your natural instinct is to help wherever you can, exercise discernment right now. Not everyone who approaches you will have honest intentions."
    },
    {
        "name": "Sagittarius",
        "horoscope": "You are likely to channel your energy into sports and physical activities to keep your stamina levels up. Today, money seems to be flowing out more than coming in, and accumulating wealth may prove to be a genuine challenge. Social gatherings and events will present the perfect opportunity to build stronger connections with influential and prominent individuals. Keep the flame of love alive and nurture it like something precious. Immerse yourself in work that has a creative dimension and allows you to express your talents. Be careful to hold your tongue and avoid making sharp or hurtful remarks if you're pulled into an argument. If you have been feeling like fortune has been working against you for a while, today is the day when things begin to feel divinely blessed.\n\nFurther validation of your career and business success may arrive today, Sagittarius. You're likely feeling energized and motivated to keep pushing the boundaries of what you've already achieved. However, the weight of increasing responsibilities may begin to cut into your personal and social time, leaving you wondering if your friends have drifted away. Rest assured, they haven't — but you'll feel much better if you consciously carve out a few hours each week for the people who matter to you. After all, they're right when they say that all work and no play makes for a dull day."
    },
    {
        "name": "Capricorn",
        "horoscope": "Your health is in excellent shape today, so there's nothing to worry about on that front. However, any dealings with banks or financial institutions need to be handled with great caution and attention to detail. Engaging in social activities with your family will keep everyone in a cheerful and relaxed frame of mind. A personal relationship may come under strain due to a clash of differing opinions. Those who are still searching for employment must put in extra effort today — only through sincere and consistent hard work will you be able to secure the position you're aiming for. You might spend some time with a friend today, but it's best to avoid alcohol during this time, as it will only be a waste of your time and energy. Your spouse may feel a little hurt today upon learning about a secret from your past.\n\nSuccess is flowing into all areas of your life and filling you with a deep sense of joy and fulfillment, Capricorn. The potential downside, however, is that you might be overdoing it in your pursuit of perfection. Are you putting in far more hours than necessary? Be smart about how you manage your energy. Pushing yourself beyond what's needed could lead to unnecessary stress and physical exhaustion. That kind of burnout won't serve your goals at all. Learn to pace yourself wisely."
    },
    {
        "name": "Aquarius",
        "horoscope": "A genuine smile is the most powerful remedy for all the challenges you face — so wear it freely. Those who have been spending money recklessly up until now must bring that behavior under control starting today and make a conscious effort to begin saving. Family members or your spouse may create some tension and unease. Your day could be mildly disrupted by the interference or involvement of your spouse's family members. Postpone any new projects or major expenditures for the time being. Someone close to you will request your time and company, but due to a packed schedule, you may be unable to fulfill their wish — leaving both you and them feeling disappointed. The health of your spouse may see a slight decline today.\n\nYour hard work, enthusiasm, and unwavering dedication are now beginning to yield tangible financial rewards, Aquarius. New opportunities to profit from your creative and artistic gifts may be presenting themselves. The challenge, however, is that you may be working so intensely that even though inspiration is knocking at your door, you're too mentally and physically drained to answer it. Take a moment to thoughtfully rework your daily schedule so that you can achieve the maximum output in the minimum amount of time."
    },
    {
        "name": "Pisces",
        "horoscope": "Spiritual wisdom from a wise and saintly person will bring you a sense of peace and inner comfort. Keep your temper well in check and be kind and respectful toward everyone in your workplace. Straying from this path of professionalism and courtesy could cost you your job, which in turn would directly harm your financial stability. Head out in the evening with friends, as it will do your spirit a world of good. Love reigns supreme in your heart and mind today. Success is absolutely within your reach — provided you make the necessary changes one deliberate step at a time. You will make a meaningful commitment to those who depend on you for support and guidance. In certain situations, you may take your partner for granted without realizing it, which could spark a disagreement between you.\n\nThose closest to you might be feeling a little concerned about your well-being, Pisces. Overworking yourself may have left you feeling somewhat less than your best — perhaps even slightly feverish or nursing a mild headache. If this is the case, today is a wonderful day to slow down, stay home, and allow your body and mind to rest and recover. Don't worry about your success taking a hit — it is well-established and will continue in your absence. Take this break and return to the helm tomorrow feeling refreshed and renewed."
    }
];