/**
 * Daily Horoscope Data
 * Includes daily horoscope predictions.
 */

const DAILY_HOROSCOPE_DATA = [
    {
        "name": "Aries",
        "horoscope": "Take special care, particularly while consuming uncovered food. However, avoid unnecessary stress as it will only create mental strain. There is a strong chance of gaining financial benefits today, but engaging in charity and donations will bring you inner peace. An old friend might reach out in the evening, reviving fond memories. Today you will feel aligned with your partner’s emotions—yes, it’s a sign that you are truly in love! You will be filled with excellent ideas, and the activities you choose may yield results beyond expectations. Your marriage will experience a beautiful phase today. Preparing something special with your loved one could further enhance your bond.\n\nYou may sit at your computer briefly to look up something online and end up spending most of the afternoon deeply absorbed in what you discover, Aries. You could come across fascinating information related to mysticism and the occult. This has always intrigued you, and once you begin exploring it, you may not want to stop. Consider joining a workshop and connecting with others who share your interest."
    },
    {
        "name": "Taurus",
        "horoscope": "You are likely to take part in a sporting activity that helps maintain your physical fitness. Avoid making impulsive decisions, especially during important financial negotiations. An evening spent with friends will be enjoyable. You may struggle to make your partner understand your perspective. Today, you might prefer distancing yourself from relatives and heading to a peaceful place. You will enjoy a calm and relaxed time with your spouse. Businesspersons should consider reviving stalled plans today.\n\nYou’ve always been financially savvy, Taurus, but today your skills seem heightened. You’ve explored the abundance of free investment resources available online and absorb the information quickly. Your natural financial wisdom helps you distinguish reliable advice from misleading information. As a result, both your portfolio and your mood benefit instantly!"
    },
    {
        "name": "Gemini",
        "horoscope": "Your energy levels will be high, allowing you to complete pending tasks efficiently. Avoid overspending just to impress others. Ensure you have everyone’s approval before making changes to your home environment. A special friend may comfort you and wipe away your tears. Communication will be your strongest asset today. The evening with your spouse could turn into one of the best moments of your life. It may feel frustrating when family members insist you do certain things over the weekend, but staying calm will serve you well.\n\nStay alert today, Gemini, as you might meet the person of your dreams—or even literally stumble upon unexpected money. It could be an unusual day, so remain attentive and open to possibilities. If a tempting new business opportunity arises, avoid accepting it immediately. Gather all the details and review them once things settle down."
    },
    {
        "name": "Cancer",
        "horoscope": "Begin your day with yoga and meditation. This practice will benefit you and help sustain your energy throughout the day. Long-pending dues and arrears are likely to be recovered. Strengthen your sense of usefulness through positive thoughts and offer helpful suggestions to support your family members. Love empowers you with a reason to cherish relationships. Drive carefully while returning home from work at night, as carelessness could lead to an accident and health issues lasting several days. You and your spouse may receive wonderful news today. If you have spare time, consider using it to repair or organize things at home.\n\nA shift in profession—or at least in hobbies—may be indicated for you, Cancer. Modern technological developments have captured your attention, especially filmmaking, which sparks your creativity. Perhaps it’s time to enroll in a weekend workshop or invest in that video camera you’ve been considering. This change will refresh and uplift you."
    },
    {
        "name": "Leo",
        "horoscope": "Unwanted thoughts may trouble your mind. Engage in physical activity, as an idle mind often breeds negativity. You may spend considerably on small household items today, which could cause mental stress. Your parents’ health requires extra care and attention. A period of loneliness seems to be ending as you may encounter your soulmate. While spending time alone can be beneficial, overthinking may create anxiety. Speaking with an experienced person about your concerns would help. Your spouse will express abundant love and enthusiasm today. The stars suggest a short, enjoyable trip with people close to you.\n\nYou may feel drawn toward distant places, Leo. Today you might stop by a travel agency and gaze at captivating images of destinations like Thailand, Hong Kong, or New Zealand. The visuals are tempting. Go ahead and plan such a journey, even if it’s only a temporary escape. Your desire to travel may reflect a deeper restlessness that needs resolution."
    },
    {
        "name": "Virgo",
        "horoscope": "Avoid unnecessary self-criticism as it may lower your morale. Your financial situation is expected to improve later in the day. Social interactions with family will create a relaxed and pleasant atmosphere. Sharing a candlelight meal with your beloved can strengthen your bond. Spending time with an elder family member today may help you understand life’s deeper aspects. Your spouse may surprise you by letting go of past disagreements and embracing you lovingly. Today, you will realize the true value of loyal friends.\n\nEven positive change can feel intimidating, Virgo. You may hesitate about accepting a new job or upgrading your home. However, a valuable opportunity is presenting itself. Ignoring it may lead to long-term regret. What is happening is ultimately beneficial, so reach out confidently and seize the chance."
    },
    {
        "name": "Libra",
        "horoscope": "Consider quitting smoking, as it will support your physical well-being. You may earn some additional income today if you act wisely. Someone you trust might not be revealing the complete truth, but your persuasive skills will help resolve upcoming issues. Neglecting your partner could create tension at home. You may guide your children on managing time effectively and using it productively. Your spouse might not meet your daily expectations today, affecting your mood. You could find yourself missing someone special.\n\nMany opportunities surround you, Libra, and you may feel tempted to grab them all. However, a discerning approach will help you make the most of favorable circumstances. Travel appears likely, as does further education. This might mean enrolling in a cooking class or even pursuing a long-held dream such as business school. Embrace it confidently!"
    },
    {
        "name": "Scorpio",
        "horoscope": "Outdoor sports may appeal to you, while meditation and yoga will prove beneficial. An unexpected source could bring financial gain today, easing monetary concerns. Social gatherings will be enjoyable, but avoid revealing personal secrets. Your somber mood might create tension with your spouse. Still, the day is favorable, allowing you to carve out meaningful time for yourself. Your spouse might disrupt one of your plans—maintain patience. Those living away from family may deeply miss home and should connect with loved ones to feel better.\n\nA financial windfall may come your way today. Handle it carefully, Scorpio, and invest it wisely for long-term benefit. Your curiosity about mysterious or esoteric subjects may grow stronger. Visiting a library to explore books on these topics could be enriching."
    },
    {
        "name": "Sagittarius",
        "horoscope": "Avoid daydreaming unrealistically and instead conserve your energy for meaningful pursuits. Speculative activities could bring profits. Pay attention to children’s needs along with home beautification, as children bring life and joy into a house. Stay cautious, as someone may attempt to damage your reputation. Be authentic in conversations; pretending will not serve you well. A serious disagreement with your spouse is possible today. You may indulge your love for food and try delicious or exotic dishes at a restaurant.\n\nA shift in surroundings seems likely, Sagittarius. Whether voluntary or not, the coming days may feel chaotic. Fortunately, your organizational skills will shine. Taking charge efficiently will help complete tasks swiftly and successfully."
    },
    {
        "name": "Capricorn",
        "horoscope": "Your health will flourish when you share happiness with others. Financially, things appear to strengthen, and money lent previously may be returned today. Someone at home might feel irritated by your recent behavior. Emotional disturbances could surface. Favorable planetary influences will provide several reasons for happiness. Expenses today might strain your relationship with your spouse. Expressing your true thoughts and feelings will help deepen your love.\n\nYou may worry about job security today, Capricorn, but such fears are likely unfounded. Workplace changes may create instability, so it’s best to stay focused and avoid involvement. Continued dedication could result in recognition, possibly in the form of a bonus or promotion. You deserve the reward."
    },
    {
        "name": "Aquarius",
        "horoscope": "Your mind will remain open to positive influences. Today, you may earn money independently without outside assistance. You will spend valuable time with family and friends. A special friend may comfort you emotionally. Engaging with an elder family member could help you gain wisdom about life. The evening with your spouse might become one of the most memorable moments. You may indulge in delicious cuisine or visit a restaurant offering exotic dishes.\n\nA powerful connection with someone may be difficult to ignore today, Aquarius. Whether newly met or recently encountered, this individual could leave a strong impression on you. It’s uncertain whether this will be fleeting or long-term, but the excitement you feel is undeniable."
    },
    {
        "name": "Pisces",
        "horoscope": "You must demonstrate courage and resilience when facing certain challenges. Your optimism will help you overcome difficulties with ease. Investing savings conservatively can generate financial gains. Plan something meaningful for your children, ensuring it is practical and achievable so it leaves a lasting impression. A sudden romantic interaction may leave you feeling confused. Much of your day might be spent on less important matters. Your partner may reveal a delightful side today. A religious ceremony or event could take place at home, though lingering worries may remain.\n\nYou may resonate with the idea that accumulating possessions reflects success, Pisces. Today you might add another technological gadget to your home—perhaps a scanner, digital camera, or DVD player. It’s a small reward for your hard work. If these items truly bring you joy, then you certainly deserve them."
    }
];