/**
 * Daily Horoscope Data
 * Contains daily horoscope readings.
 */

const DAILY_HOROSCOPE_DATA = [
    {
        "name": "Aries",
        "horoscope": "Your health is anticipated to remain in good shape today. Owing to your physical well-being, you may consider planning some fun activities with your friends.  The Moon's positioning may lead to unnecessary expenditure of your money. If your goal is to build savings, consider having a conversation with your spouse or parents regarding financial planning.  For some- a new member entering the family may bring along reasons to celebrate and rejoice.  Neglecting your partner's feelings may create tension and stress within the household.  Those involved in international trade are likely to achieve the outcomes they were hoping for today. Additionally, working individuals of this sign may find themselves fully utilizing their abilities at the workplace.  Make it a point to devote some time to the younger ones in your family. Failing to do so could disrupt the peace and harmony within your home.  Your spouse may become overly absorbed in professional responsibilities today, leaving you feeling neglected and disheartened.\n\nThis might turn out to be a particularly hectic day in your locality, Aries. Some kind of demonstration, march, or large public event could be taking place nearby. If you choose to attend, the noise and disarray may make it hard to follow what's happening, and the overall event may feel chaotic at best. It could also make commuting nearly impossible! Wherever possible, consider staying indoors today. Stepping out may cause more hassle than it's worth. Channel your energy into making your voice heard through voting or conscious spending instead."
    },
    {
        "name": "Taurus",
        "horoscope": "Your presence will leave a lasting impression on everyone around you today, much like a pleasant fragrance.  You are likely to receive financial gains through your children today, which will fill your heart with immense joy.  Plan something truly memorable for your younger ones. Ensure that whatever you plan is achievable so that it can actually be carried out. Your future generations will cherish the gift you give them for years to come. Love is a feeling meant to be experienced deeply and shared wholeheartedly with your partner. Switching careers could open better doors for you. You might consider leaving your current position and exploring a new domain like Marketing, which could suit your strengths well. Those often criticized for not spending enough time with family can make an effort to carve out some quality moments together. However, an unexpected responsibility may crop up and disrupt those plans.  If you have been feeling unlucky for quite some time, today is the day when fortune is likely to smile upon you.\n\nA decision you may or may not take in the near future could hinge on information you receive today, Taurus. That said, don't be caught off guard if the details are unclear and require further verification. To make matters more complicated, the one person who could provide clarity might be unavailable to you! Stay patient and persistent. You'll want to arrive at a conclusion as quickly as circumstances allow."
    },
    {
        "name": "Gemini",
        "horoscope": "Exercise caution with what you consume today. Being careless about your diet could lead to health issues. An improvement in your financial situation will make it easier to settle overdue payments and pending bills.  Dedicate adequate time to your family. Allow them to feel your love and care. Spend meaningful moments with them. Give them no reason to feel ignored.  A uniquely different kind of romantic experience may be on the horizon.  You need to refine your approach toward your work to produce better results at the office, as a lack of focus could create an unfavorable impression in the eyes of your superiors.  To make the most of your leisure time, consider stepping away from the crowd and indulging in activities you genuinely enjoy. This will also bring about some positive transformations in your life.  Today, you will feel a deep sense of gratitude for your married life.\n\nAre you feeling dissatisfied or doubtful about your current career path, Gemini? Are you contemplating a shift? Word may reach you today about potential new directions to consider, but refrain from making any decisions just yet. Your thinking may not be clear-headed enough right now to weigh everything properly. Reflect on the possibilities, but allow yourself a day or two before committing to anything significant."
    },
    {
        "name": "Cancer",
        "horoscope": "Your youthful and spirited nature will come to the forefront today, putting you in a lighthearted and fun-loving mood.  A neighbor may approach you seeking a financial loan today. It is advisable to assess their reliability before agreeing to lend any money, as there is a risk of financial loss otherwise.  You are likely to be the center of attention at a family gathering today.  Spending time without your beloved may feel particularly difficult today.  This is a highly favorable period for building professional connections with people in other countries.  While keeping pace with the demands of the modern world is important, it is equally essential to recognize the value of family and make time for your loved ones whenever possible.  The day is likely to offer much-needed relief after a challenging phase in your marital relationship.\n\nYour innate psychic or intuitive abilities may feel somewhat dulled today, Cancer. The influence of surrounding energies could blur your perception of situations, which won't serve you well. Your imaginative thinking may also feel scattered and unclear. The best course of action would be to focus on yourself and your personal needs for the day. You can return to your regular rhythm starting tomorrow."
    },
    {
        "name": "Leo",
        "horoscope": "Your spouse may bring a smile to your face and lift your spirits today.  Some natives of this sign who have been seeking employment may land a job today, leading to an improvement in their financial circumstances.  Work collaboratively to create a sense of harmony within your household.  Your eyes radiate such warmth and brightness that they have the power to illuminate even the darkest nights for your beloved.  Those who are employed may encounter multiple obstacles at the workplace today. Unintentional errors could put you in a difficult position with your seniors.  The day is expected to proceed uneventfully for those in business.  During your free time, you are likely to take up tasks you had been planning and thinking about for a long time but hadn't found the opportunity to complete.  Tonight could turn into one of the most memorable and cherished evenings of your married life.\n\nThe environment around you might carry a slightly surreal quality today. If someone gives you an odd feeling, Leo, treat everything they tell you with healthy skepticism. This person may have ulterior motives and may not hesitate to bend the truth in order to serve their agenda. If their words don't impact you directly, it may not be worth your attention. If they do, make a conscious effort to verify the facts independently before taking any action. You'll be grateful that you exercised caution."
    },
    {
        "name": "Virgo",
        "horoscope": "Keep mental stress and anxiety at bay to ensure a cheerful and fulfilling day.  Refrain from spending beyond your means simply to create an impression on others.  Rally everyone for your grand get-together — that extra burst of energy you carry today will help you pull off a memorable event for your group.  The possibility of someone popping the question appears to be in the stars.  A productive day lies ahead as you get a wonderful opportunity to work toward your goals.  IT professionals may even receive an inquiry or offer from abroad.  Despite a packed schedule, you will find ways to carve out some personal time today. Use that time to engage in something creative and fulfilling.  This day is set to be one of the finest in your married life. You will experience the true joy and depth of love.\n\nCommunicating effectively may require extra patience and effort today, Virgo. A business associate or romantic partner could appear guarded, as though they are holding something back. You might pick up on an unsettling vibe and begin to wonder if something is off in your partnership. Don't hesitate to bring it up directly. Your companion may not reveal the full picture, but will likely reassure you that it has no bearing on you or your relationship. If that's the case, it is best to respect their privacy and move on."
    },
    {
        "name": "Libra",
        "horoscope": "Wear a smile — it is the most powerful remedy for all the challenges life throws at you.  Sit down with your spouse today to discuss financial matters and put together a plan for securing your future wealth.  Today is a favorable day to extend a helping hand to those around you.  Stay open to new relationships that can add happiness and color to your life.  Your inner strength will serve as an excellent ally in making the day a productive and satisfying one at work.  You may feel inclined to engage in some of your favorite activities today, but an overwhelming amount of work is likely to stand in the way.  Today, your partner may reveal a delightful and unexpected side of themselves.\n\nMessages arriving from a distant region or another country — perhaps via fax, email, or an online platform — may not be entirely reliable today, Libra. If any piece of information you come across triggers doubt or skepticism, take the time to investigate it on your own and cross-check the facts. Avoid taking any news at face value today. The channels of communication, both human and technological, appear to be particularly unreliable at this time."
    },
    {
        "name": "Scorpio",
        "horoscope": "Incorporate meditation and yoga into your daily routine to strengthen both your body and your mental resilience.  Those who have taken loans may find it challenging to keep up with repayments today.  A period of unease may be on the horizon, but the support of your family will help you navigate through it.  Romantic possibilities seem to present themselves — though they may not last very long.  Set aside your ego when it comes to making important decisions — be open to hearing what those around you, including subordinates, have to offer.  Today, you'll have intentions of reorganizing your living space and tidying things up, but finding time to actually do so will prove difficult.  In the midst of an ordinary married life, this day will feel like a special and indulgent treat.\n\nMaintaining contact with a romantic partner could prove to be challenging today, Scorpio, almost enough to cause a mild sense of unease. Resist the urge to draw negative conclusions about the state of your relationship. The reason for the silence is most likely beyond your partner's control, and could be tied to something sudden and unforeseen, or even something as simple as a technical glitch. Stay calm and keep the faith."
    },
    {
        "name": "Sagittarius",
        "horoscope": "Pay close attention to your health and bring order to the aspects of your life that feel unsettled.  Unresolved issues may become more complicated, and financial concerns could weigh heavily on your mind.  A disagreement with your spouse could lead to emotional distress and mental tension.  There is no reason to burden yourself with unnecessary worry.  One of life's greatest lessons is learning to accept the things that are beyond our power to change.  The possibility of someone proposing a relationship appears to be on the horizon.  Work-related pressures continue to linger, leaving little room for family and social interactions.  You are someone who values personal space, and today you are likely to enjoy a generous amount of time to yourself. Use it to engage in a hobby, hit the gym, or simply unwind.\n  This day holds great promise for your married life. Take a moment to express how deeply you love your partner.\n\nAre you dealing with any issues related to electricity or heating at home, Sagittarius? If so, getting a technician or repair professional to visit today may not be easy. The problem could be affecting the entire neighborhood. You might need to dig out the candles and torches to get through the evening. Try not to let this dampen your spirits. It is a temporary inconvenience that will be resolved before long. Look at it as an unexpected little adventure!"
    },
    {
        "name": "Capricorn",
        "horoscope": "Pay attention to your health and overall well-being, as neglecting it could lead to complications down the line.  Financial troubles that have been weighing on you may find resolution today, and you could benefit from some monetary gains.  A relaxed evening at the cinema or a cozy dinner with your spouse is likely to put you in a warm and pleasant mood.  Failing to pay enough attention to your partner's feelings could create tension and unease at home.  Senior colleagues and relatives are likely to extend valuable support and guidance.  Students are strongly advised to avoid wasting their time in idle socializing. This is a critical period in their academic journey where focus and dedication are essential for progress.  The stress arising from your spouse's behavior might begin to affect your health adversely.\n\nA friend or neighbor you've been trying to get in touch with may be on the go throughout the day, Capricorn, making them difficult to reach. Phone calls and emails are unlikely to get through, as they may simply be too caught up to check for messages. The most effective approach might be to get in the car and head to wherever they are most likely to be found. Opt for the back roads when you do — the main routes are probably backed up with heavy traffic!"
    },
    {
        "name": "Aquarius",
        "horoscope": "Beginning your day with Yoga and Meditation can set a positive tone for everything that follows. This practice will prove beneficial and help you sustain your energy levels right through the day.  Long-overdue dues and outstanding amounts are finally likely to be recovered today.  Family members or your spouse may stir up some tensions.  Your partner's unpredictable behavior could put a damper on your mood.  It is an excellent day to launch new initiatives and put fresh plans into motion.  While socializing with acquaintances is perfectly fine, pouring out your innermost secrets to people whose intentions are unknown is simply an unwise use of your trust and emotions.  A relative, friend, or neighbor could introduce some friction into your marital life today.\n\nThis may not be the most suitable day to deal with matters involving money, Aquarius. Your mind may not be operating at its sharpest, making you susceptible to errors that could cause future problems. If possible, also steer clear of any creative work today, as your thoughts might feel foggy and the results are unlikely to satisfy you. On the brighter side, this is a perfectly good day for attending to routine responsibilities that don't demand intense concentration."
    },
    {
        "name": "Pisces",
        "horoscope": "Your friends will rally around you with their support and keep your spirits high.  A colleague at work could potentially take one of your valuable belongings today, so stay alert and keep a watchful eye on your possessions.  Both your parents and friends will go out of their way to ensure your happiness.  An unexpected and spontaneous romantic encounter is likely to brighten your mood and lift your spirits.  Those working in the fields of art and theatre may come across several exciting new avenues to express and showcase their creative talents.  People who have been caught up in a whirlwind of activity over the past few days will finally get to enjoy some peaceful time to themselves.  You may find yourself falling in love with your spouse all over again today — because they truly deserve every bit of it.\n\nA misplaced item could send everyone in your household on a frantic search through every corner of the home, Pisces — and it may well end without success. Any guests present may also join in to help with the hunt. The object is most likely somewhere in a common area — a larger shared space — perhaps tucked away among other belongings. If no one manages to locate it, try not to stress about it for now. There's a good chance it will turn up on its own when you least expect it."
    }
];