/**
 * Horoscope Data
 * Contains daily horoscopes, profiles, and yearly forecasts for all 12 zodiac signs.
 */

const HOROSCOPE_DATA = [
    {
        "name": "Aries",
        "date": "Mar 21 - Apr 19",
        "icon": "♈",
        "element": "Fire",
        "ruling_planet": "Mars",
        "keywords": ["Courageous", "Determined", "Confident"],
        "traits": "Aries loves to be number one, so it’s no surprise that these audacious rams are the first sign of the zodiac. Bold and ambitious, Aries dives headfirst into even the most challenging situations.",
        "strengths": ["Courageous", "Determined", "Confident", "Enthusiastic", "Optimistic"],
        "weaknesses": ["Impatient", "Moody", "Short-tempered", "Impulsive", "Aggressive"],
        "compatibility": "**Most Compatible:** Leo, Sagittarius, Gemini, Aquarius.\n**Least Compatible:** Cancer, Capricorn.",
        "horoscope": "Your generous nature is likely to create many pleasant moments today. Keep your temper in check and maintain kindness toward colleagues at work. Straying from this approach could put your job at risk and negatively affect your finances. Enjoy cheerful moments with friends and family. Opportunities for a fresh romantic bond are strong, but avoid sharing private or sensitive details too soon. Stay focused on your ambitions and keep your plans to yourself until success is secured. Your mind will be buzzing with ideas today, and the actions you choose can bring rewards far beyond what you expect. You will truly recognize how important you are to your partner.\n\nWelcome to a promising day, Aries. The planetary energy supports open communication and social interaction. Make the most of it by connecting with loved ones or spending quality time together. Hosting friends, planning a meal, or even organizing a casual get-together can lift your spirits. You put in serious effort every day, so allow yourself to relax and enjoy life today.",
        "yearly_forecast": "**2026 Overview:** A powerful year for inner reflection and professional growth. Planetary transits bring unexpected opportunities. Focus on self-analysis to prepare for big transformations.\n\n**Love:** Relationships deepen through shared activities. Passion is high, but communication is crucial to avoid misunderstandings.\n\n**Career:** Immense opportunities await. Networking and seizing unexpected offers will lead to success.\n\n**Health:** Prioritize sleep and stress management. Improved productivity depends on balancing your energy.\n\n**Education:** An above-average year. Success in competitive exams is likely. Students in tourism or media will thrive.\n\n**Family & Travel:** Domestic life may see mixed results; use logic to resolve conflicts. Long-distance travel brings mental peace."
    },
    {
        "name": "Taurus",
        "date": "Apr 20 - May 20",
        "icon": "♉",
        "element": "Earth",
        "ruling_planet": "Venus",
        "keywords": ["Reliable", "Patient", "Practical"],
        "traits": "Taurus is an earth sign represented by the bull...",
        "strengths": ["Reliable", "Patient", "Practical", "Devoted", "Responsible", "Stable"],
        "weaknesses": ["Stubborn", "Possessive", "Uncompromising"],
        "compatibility": "**Most Compatible:** Virgo, Capricorn, Cancer, Pisces.\n**Least Compatible:** Leo, Aquarius.",
        "horoscope": "Encourage yourself to adopt a more positive outlook. This will strengthen your confidence and adaptability while helping you release negative feelings such as fear, jealousy, or resentment. Those who attempt to avoid taxes may land themselves in serious trouble today, so stay on the right side of the law. It’s a favorable time to refresh and strengthen relationships with relatives. Your love life feels secure and resilient. Productivity can increase significantly if you remain fully focused on your responsibilities. However, much of your time may get spent on unnecessary matters today. Your spouse is likely to shower you with extra attention.\n\nYou may feel an urge to step out and do something different today, Taurus—and that’s a great idea. Calling a few friends and planning an evening together shouldn’t be difficult. You might also enjoy checking local listings for an event, talk, or gathering that sparks your interest. If there’s a place you’ve been meaning to explore, make today the day you go. Use your time wisely and enjoy the experience.",
        "yearly_forecast": "**2026 Overview:** A spectacular year of stability and prosperity. Fresh opportunities in personal life and finances emerge.\n\n**Love:** Meaningful connections flourish. It's a time to build a partnership that feels like home, moving away from fleeting flings.\n\n**Career:** Financially prosperous! Jupiter boosts income and lifestyle, but caution against overspending is advised. Investments look promising.\n\n**Health:** Watch for digestive issues; proactive check-ups are key. Mental peace comes from a stable routine.\n\n**Education:** Academic performance peaks early in the year. High school students may relocate for better opportunities.\n\n**Family & Travel:** Family life requires patience due to dynamic shifts. Step out of your comfort zone—cultural trips are transformative."
    },
    {
        "name": "Gemini",
        "date": "May 21 - Jun 20",
        "icon": "♊",
        "element": "Air",
        "ruling_planet": "Mercury",
        "keywords": ["Adaptable", "Outgoing", "Intelligent"],
        "traits": "Have you ever been so busy that you wished you could clone yourself...",
        "strengths": ["Gentle", "Affectionate", "Curious", "Adaptable", "Ability to learn quickly"],
        "weaknesses": ["Nervous", "Inconsistent", "Indecisive"],
        "compatibility": "**Most Compatible:** Libra, Aquarius, Aries, Leo.\n**Least Compatible:** Virgo, Pisces.",
        "horoscope": "An ideal day to make a fresh start toward better health habits. Financial gains are possible if you invest your savings in safe and steady options. Strive to be a guiding light and maintain high standards in both life and work. Your warmth, compassion, and desire to help others will naturally create harmony within your family. A third party’s involvement may create tension between you and your partner. Connect with experienced individuals who can offer insight into future possibilities. Laughter and joy dominate the day as most things unfold in your favor. Outside interference could cause some strain in your marital relationship today.\n\nTry channeling your thoughtful and philosophical ideas into creative expression today, Gemini. Writing can be especially satisfying now. Even if this is new territory for you, it’s the perfect time to experiment. Starting a journal can help your thoughts take shape and evolve. You might also explore poetry or storytelling as an outlet for your imagination.",
        "yearly_forecast": "**2026 Overview:** One of your luckiest years! Major developments in love and career await as planetary shifts spark independence.\n\n**Love:** New, meaningful relationships form early. Intellectual connection is vital—if the mind isn't engaged, the heart won't follow.\n\n**Career:** Major professional development is on the horizon. Your unique voice and ideas are your greatest assets.\n\n**Health:** Balance nervous energy with breathwork or yoga. Mental wellness is as important as physical fitness this year.\n\n**Education:** Excellent for competitive exams. Creativity is high, but managing time is essential for success.\n\n**Family & Travel:** Married life flourishes. Travel for work and exploration is favored—consider visiting Italy or Scotland to feed your curiosity."
    },
    {
        "name": "Cancer",
        "date": "Jun 21 - Jul 22",
        "icon": "♋",
        "element": "Water",
        "ruling_planet": "Moon",
        "keywords": ["Tenacious", "Imaginative", "Loyal"],
        "traits": "Cancer is a cardinal water sign...",
        "strengths": ["Tenacious", "Highly imaginative", "Loyal", "Emotional", "Sympathetic", "Persuasive"],
        "weaknesses": ["Moody", "Pessimistic", "Suspicious", "Manipulative", "Insecure"],
        "compatibility": "**Most Compatible:** Scorpio, Pisces, Taurus, Virgo.\n**Least Compatible:** Aries, Libra.",
        "horoscope": "Protecting your mental well-being is essential, as it forms the foundation of spiritual growth. The mind acts as a gateway, shaping how you experience both positive and negative situations. Today, you may feel inclined to travel or spend freely, but this could lead to regret later. Children lend a hand with household responsibilities. A romantic meal shared by candlelight enhances emotional closeness. It’s a rewarding day at work, with appreciation coming from colleagues and recognition from your boss. Business owners may also see gains. Use your free time wisely by reconnecting with old friends. A delightful surprise could add excitement to your married life.\n\nYou may crave some personal space today, Cancer, and taking it is perfectly healthy. Being constantly surrounded by others can drain you emotionally if you don’t pause to reconnect with yourself. Your sensitive nature requires regular moments of reflection. Make room in your schedule today to nurture your emotional balance.",
        "yearly_forecast": "**2026 Overview:** A transformative year. Career struggles fade, leading to a lucky cycle when Jupiter enters your sign mid-year.\n\n**Love:** Early challenges lead to blossoming romance. Jupiter boosts joy in family and secure bonding.\n\n**Career:** A great period for finding work or launching projects. Trust your gut—your visibility and influence are increasing.\n\n**Health:** Vitality is good initially, but avoid overworking. Support your emotional well-being with nutrient-rich foods.\n\n**Education:** Self-discovery is key. Admissions to prestigious universities are possible, but discipline is required.\n\n**Family & Travel:** Focus on domestic peace early in the year. Travel for business expansion is likely."
    },
    {
        "name": "Leo",
        "date": "Jul 23 - Aug 22",
        "icon": "♌",
        "element": "Fire",
        "ruling_planet": "Sun",
        "keywords": ["Creative", "Passionate", "Generous"],
        "traits": "Roll out the red carpet, because Leo has arrived...",
        "strengths": ["Creative", "Passionate", "Generous", "Warm-hearted", "Cheerful", "Humorous"],
        "weaknesses": ["Arrogant", "Stubborn", "Self-centered", "Lazy", "Inflexible"],
        "compatibility": "**Most Compatible:** Aries, Sagittarius, Gemini, Libra.\n**Least Compatible:** Taurus, Scorpio.",
        "horoscope": "Your steady optimism is likely to pay off, helping you succeed in your current efforts. Innovative thinking may open doors to earning extra income. Marriage-related proposals may surface for those who are eligible. A meaningful conversation or message from your partner will lift your spirits. Think carefully before committing to expensive plans or agreements. If you feel disconnected from money, love, or family matters, seeking spiritual guidance could bring peace. Today, you may rediscover the spark in your relationship with your spouse.\n\nYou may feel a strong desire to assert your independence today, Leo, even if others have different expectations. While personal freedom matters greatly to you, compromise may be necessary to avoid conflict. Dividing your time between your own needs and those of loved ones could be the most practical approach. If explaining your need for space feels difficult, this balance may keep everyone content.",
        "yearly_forecast": "**2026 Overview:** A fulfilled journey from slow starts to mid-year popularity. Prepare for personal reinvention.\n\n**Love:** Excellent shape early in the year. It's an ideal time to gain clarity and strengthen bonds with your partner.\n\n**Career:** Partnerships drive success. Teamwork is your golden ticket, so share the spotlight to achieve your big goals.\n\n**Health:** Protect your heart health with cardio. Seasonal minor issues may arise, but overall vitality is strong.\n\n**Education:** A year of development and leadership in potential student roles. Good results are expected.\n\n**Family & Travel:** Family feels secure and harmonious. You crave luxury with adventure—grand travel memories await."
    },
    {
        "name": "Virgo",
        "date": "Aug 23 - Sep 22",
        "icon": "♍",
        "element": "Earth",
        "ruling_planet": "Mercury",
        "keywords": ["Loyal", "Analytical", "Kind"],
        "traits": "Virgo is an earth sign historically represented by the goddess of wheat...",
        "strengths": ["Loyal", "Analytical", "Kind", "Hardworking", "Practical"],
        "weaknesses": ["Shyness", "Worry", "Overly critical of self and others", "All work and no play"],
        "compatibility": "**Most Compatible:** Taurus, Capricorn, Cancer, Scorpio.\n**Least Compatible:** Gemini, Sagittarius.",
        "horoscope": "Visualize something uplifting and beautiful to raise your spirits today. Financially, you may not need to rely on your own funds, as support from an elder at home is possible. If you offer guidance to others today, remain open to receiving advice as well. A friendship could naturally evolve into something more romantic. Spending time with experienced individuals may give you valuable insight into future opportunities. Married Virgos with children might face complaints about lack of time. Doubting your partner’s sincerity could create unnecessary strain in your relationship.\n\nYou may feel inspired to step out for a visit or short trip today, Virgo. It’s likely been a while since you allowed yourself such a break. This change of routine can be refreshing, and others will enjoy your company too. Whether you travel with family or go solo, take advantage of the chance to explore somewhere new or reconnect with people you’ve missed.",
        "yearly_forecast": "**2026 Overview:** Important lessons and big wins. Eclipses shake up relationships, challenging you to find joy in your inner world.\n\n**Love:** Commitment is tested. Whether single or attached, focus on relationships that support your personal growth and joy.\n\n**Career:** Saturn tests patience, but consistent effort pays off. Expect recognition for your efficiency in the second half.\n\n**Health:** Avoid overworking your digestive system. Schedule lighter meals and ensure you take mental breaks.\n\n**Education:** Hard work is needed after mid-year. Organization is your superpower and will lead to success.\n\n**Family & Travel:** Family life may need extra effort. You prefer organized trips—traditional festivals will delight you."
    },
    {
        "name": "Libra",
        "date": "Sep 23 - Oct 22",
        "icon": "♎",
        "element": "Air",
        "ruling_planet": "Venus",
        "keywords": ["Cooperative", "Diplomatic", "Gracious"],
        "traits": "Libra is an air sign represented by the scales...",
        "strengths": ["Cooperative", "Diplomatic", "Gracious", "Fair-minded", "Social"],
        "weaknesses": ["Indecisive", "Avoids confrontations", "Will carry a grudge", "Self-pity"],
        "compatibility": "**Most Compatible:** Gemini, Aquarius, Leo, Sagittarius.\n**Least Compatible:** Cancer, Capricorn.",
        "horoscope": "Nurture a peaceful mindset and release feelings of resentment, as negativity can harm you more than you realize. Financial stability remains strong today, with planetary support opening multiple earning opportunities. Someone you trust may not be completely honest, but your persuasive skills will help you navigate upcoming challenges. Romantic relationships may feel strained due to outside interference. Your dedication and effort at work are likely to yield impressive results. While sports and physical activity are beneficial, avoid letting them interfere with academic responsibilities. Concerns about your spouse’s health could cause some stress today.\n\nDeep thinking and clear communication are highlighted today, Libra. These natural strengths are amplified, making it a perfect time to express yourself. Writing in a journal or having meaningful conversations can help release lingering concerns. If unresolved issues have been weighing on you, consider addressing them directly with those involved. This is an excellent day to clear the air and find resolution.",
        "yearly_forecast": "**2026 Overview:** Big changes and new horizons! Adventure and travel call in the first half, followed by career expansion.\n\n**Love:** March turns up the heat. Drop illusions and communicate clearly. Boundaries will bring you closer to true intimacy.\n\n**Career:** A major level-up awaits. A new role aligning with your values is likely, especially after June.\n\n**Health:** Hydration is key for skin and kidney health. Recovery from past ailments looks very favorable.\n\n**Education:** Collaborative learning brings success. Early months are ideal for educational planning.\n\n**Family & Travel:** Family bonds strengthen after mid-year. Travel for growth is indicated."
    },
    {
        "name": "Scorpio",
        "date": "Oct 23 - Nov 21",
        "icon": "♏",
        "element": "Water",
        "ruling_planet": "Pluto",
        "keywords": ["Resourceful", "Brave", "Passionate"],
        "traits": "Scorpio is one of the most misunderstood signs...",
        "strengths": ["Resourceful", "Brave", "Passionate", "Stubborn", "A true friend"],
        "weaknesses": ["Distrusting", "Jealous", "Secretive", "Violent"],
        "compatibility": "**Most Compatible:** Cancer, Pisces, Virgo, Taurus.\n**Least Compatible:** Leo, Aquarius.",
        "horoscope": "A flare of temper could spark disagreements or confrontations today. Influential individuals may be willing to support projects that carry a sense of quality or uniqueness. Your rigid attitude might disturb family harmony, so pay attention to parental advice and remain flexible. Feelings of missing true love may surface, but remember that circumstances change with time, including your romantic life. Continue working silently toward your objectives without revealing your strategies prematurely. Make an effort to give time and attention to relationships that truly matter. You may initially feel overlooked by your spouse, only to realize later that they were busy arranging something special for you.\n\nYou could feel pressured into handling something you’re not comfortable with today, Scorpio. Perhaps a prior commitment or someone else’s expectations are weighing on you. If this causes unease, communicate openly rather than suppressing it. The day favors clear expression and mutual understanding. Rescheduling or adjusting plans may prevent unnecessary resentment later.",
        "yearly_forecast": "**2026 Overview:** A dynamic mix of opportunities. Cosmic shifts alter your course, bringing meaningful growth early in the year.\n\n**Love:** Singles might find someone special early. Existing relationships strengthen, with serious commitments like marriage possible.\n\n**Career:** Education and new skills are highlighted. It's a fantastic year to learn something that adds value to your toolkit.\n\n**Health:** Generally robust physical health. Minor ailments will be short-lived, so stay active.\n\n**Education:** Hard work pays off for exam takers. Travel for education may bring clarity.\n\n**Family & Travel:** Harmony prevails in the first half. Travel with friends or family is encouraged."
    },
    {
        "name": "Sagittarius",
        "date": "Nov 22 - Dec 21",
        "icon": "♐",
        "element": "Fire",
        "ruling_planet": "Jupiter",
        "keywords": ["Generous", "Idealistic", "Funny"],
        "traits": "Represented by the archer, Sagittarius is always on a quest...",
        "strengths": ["Generous", "Idealistic", "Great sense of humor"],
        "weaknesses": ["Promises more than can deliver", "Very impatient", "Will say anything no matter how undiplomatic"],
        "compatibility": "**Most Compatible:** Aries, Leo, Libra, Aquarius.\n**Least Compatible:** Virgo, Pisces.",
        "horoscope": "Trust your inner judgment today and act decisively, even if the choices feel bold. Speculative efforts may bring financial gains. Valuable lessons may come from your children, whose innocence and positivity have a powerful influence on those around them. Your love life carries a unique sweetness and warmth today. Avoid yielding to external pressure when making important business decisions. You may wish to spend time caring for your mother, but urgent matters could interfere and cause concern. Married life appears especially harmonious and fulfilling today.\n\nYou may notice that someone close to you, possibly a family member, needs support today, Sagittarius. They might hesitate to ask due to pride, but that shouldn’t stop you from offering help. If you see an opportunity to assist, step in without waiting to be asked. Your kindness will be deeply appreciated, and you’ll feel uplifted knowing you made a positive difference.",
        "yearly_forecast": "**2026 Overview:** A supportive start with Jupiter aiding plans. You must balance your free spirit with Saturn's demand for discipline.\n\n**Love:** Professional life may distract initially, but Venus brings rewards later. Stability becomes more attractive than fleeting fun.\n\n**Career:** Mixed outcomes lead to success if you persist. Hard work is non-negotiable, but new avenues open after May.\n\n**Health:** Optimistic outlook, but watch for mental pressure. Meditation or yoga will help keep your fire balanced.\n\n**Education:** Unconventional fields call to you. Internships abroad will expand your horizons.\n\n**Family & Travel:** Mutual support strengthens family bonds. Your adventurous spirit will love international festivals."
    },
    {
        "name": "Capricorn",
        "date": "Dec 22 - Jan 19",
        "icon": "♑",
        "element": "Earth",
        "ruling_planet": "Saturn",
        "keywords": ["Responsible", "Disciplined", "Self-control"],
        "traits": "The last earth sign of the zodiac, Capricorn is represented by the sea goat...",
        "strengths": ["Responsible", "Disciplined", "Self-control", "Good managers"],
        "weaknesses": ["Know-it-all", "Unforgiving", "Condescending", "Expecting the worst"],
        "compatibility": "**Most Compatible:** Taurus, Virgo, Scorpio, Pisces.\n**Least Compatible:** Aries, Libra.",
        "horoscope": "Your confidence and positive attitude are likely to impress those around you. A family member’s health concern could create financial strain, but their well-being should take priority over monetary worries. Children may test your patience today, so use affection and understanding to keep things calm. Remember that love grows when it is expressed. Outside interference could cause tension between you and your partner. New ventures look attractive and may promise solid returns. Your politeness and charm will leave a strong impression, though only a few will understand the source of your influence. Your partner’s lack of energy may slow down some of your plans today.\n\nConsider picking up a pen and paper today, Capricorn. In a world dominated by screens, the physical act of writing can be surprisingly calming. Just as walking offers more than exercise alone, writing by hand engages your senses in a soothing way. Letting your thoughts flow onto paper may unlock emotions and insights that typing cannot. Give it a try and notice the difference.",
        "yearly_forecast": "**2026 Overview:** Big transitions in every area. The pressure gives way to evolution and financial refinement.\n\n**Love:** Social expansion brings joy. Existing partnerships flourish, and singles may find stable, long-term prospects.\n\n**Career:** Financial growth is the focus. Saturn helps you solidify plans, and collaboration becomes your path to the top.\n\n**Health:** Strengthen your bones with Vitamin D and resistance training to match your strong ambition.\n\n**Education:** Consistent success. Good for long-term goals and certifications due to strong concentration.\n\n**Family & Travel:** Good news from maternal relatives is likely. You prefer structured trips—relaxing or hiking adventures fit your style."
    },
    {
        "name": "Aquarius",
        "date": "Jan 20 - Feb 18",
        "icon": "♒",
        "element": "Air",
        "ruling_planet": "Uranus",
        "keywords": ["Progressive", "Original", "Independent"],
        "traits": "Despite the \"aqua\" in its name, Aquarius is actually the last air sign...",
        "strengths": ["Progressive", "Original", "Independent", "Humanitarian"],
        "weaknesses": ["Runs from emotional expression", "Temperamental", "Uncompromising", "Aloof"],
        "compatibility": "**Most Compatible:** Gemini, Libra, Aries, Sagittarius.\n**Least Compatible:** Taurus, Scorpio.",
        "horoscope": "Be mindful of your posture today to avoid strain or injury. Sitting correctly not only improves health but also boosts confidence and presence. Investing money in spiritual or charitable activities may bring mental peace and inner stability. Place family needs at the top of your priorities and share in their joys and concerns to show genuine care. A sense of pure and meaningful love may be experienced today. It’s an excellent time to put new ideas and plans into action. Differences with close associates could create tension, so stay patient. Your spouse may rekindle memories of early romance and affection today.\n\nA heightened sense of empathy and understanding surrounds you today, Aquarius, making communication especially effective. Use this energy to discuss unresolved matters or strengthen emotional bonds. If distance separates you from loved ones, consider visiting or reaching out by phone. Even if nothing urgent needs attention, openly expressing appreciation can deepen your connections.",
        "yearly_forecast": "**2026 Overview:** A year to shine! Significant growth in career and finances. The first half is for planning; the second brings breakthroughs.\n\n**Love:** Communication is your lifeline. Long-distance or online connections could surprise you. Patience is key in matters of the heart.\n\n**Career:** Saturn gives you control over your path, while Jupiter offers expansion. Property investments and financial gains look favorable.\n\n**Health:** Improve circulation with movement breaks. Consistent activity keeps your innovative mind sharp.\n\n**Education:** Excellent prospects for research and higher education, especially after May.\n\n**Family & Travel:** Family tension fades after mid-year. Professional changes in spring might inspire travel."
    },
    {
        "name": "Pisces",
        "date": "Feb 19 - Mar 20",
        "icon": "♓",
        "element": "Water",
        "ruling_planet": "Neptune",
        "keywords": ["Compassionate", "Artistic", "Intuitive"],
        "traits": "Pisces, a water sign, is the last constellation of the zodiac...",
        "strengths": ["Compassionate", "Artistic", "Intuitive", "Gentle", "Wise", "Musical"],
        "weaknesses": ["Fearful", "Overly trusting", "Sad", "Desire to escape reality"],
        "compatibility": "**Most Compatible:** Cancer, Scorpio, Taurus, Capricorn.\n**Least Compatible:** Gemini, Sagittarius.",
        "horoscope": "Practices like meditation and self-reflection will be especially helpful today. Financial conditions show signs of improvement. It’s a favorable day to connect with people you don’t often interact with. Romantic plans may face disappointment if a date doesn’t go as expected. Your creativity and artistic talents are likely to receive praise. Despite a busy schedule, you will make time for your children, and this interaction will remind you of what truly matters. Make an effort to surprise your partner regularly, or they may begin to feel overlooked.\n\nYour thoughts may feel restless and fast-moving today, Pisces, making it hard to slow down. Expressing what’s on your mind will be important. The planetary energy favors communication, so discussing your ideas with someone you trust could be helpful. Writing, sketching, or even casual doodling can give your thoughts an outlet. Explore these creative releases today.",
        "yearly_forecast": "**2026 Overview:** Introspection and rebirth. As Saturn prepares to leave, you emerge more grounded, mature, and spiritually connected.\n\n**Love:** Relationships take on a deeper meaning. You seek soul connections, and casual dating loses its appeal.\n\n**Career:** Strategic planning wins the race. It's a year to balance your dreams with reality. Artistic and healing professions continue to be favored.\n\n**Health:** Support your immunity with herbal teas and adaptogens. Your sensitive nature needs extra care during this transition.\n\n**Education:** Success in creative fields. Studying abroad or travel-related subjects is highly favored.\n\n**Family & Travel:** Manage minor family tensions with communication. Travel for relaxation is key—beaches call to your water spirit."
    }
];
