const HOROSCOPE_DATA =[
  {
    "name": "Aries",
    "date": "Mar 21 - Apr 19",
    "icon": "♈",
    "element": "Fire",
    "ruling_planet": "Mars",
    "keywords": ["Courageous", "Determined", "Confident"],
    "traits": "Aries loves to be number one, so it’s no surprise that these audacious rams are the first sign of the zodiac. Bold and ambitious, Aries dives headfirst into even the most challenging situations.",
    "strengths": ["Courageous", "Determined", "Confident", "Enthusiastic", "Optimistic"],
    "weaknesses": ["Impatient", "Moody", "Short-tempered", "Impulsive", "Aggressive"],
    "compatibility": "**Most Compatible:** Leo, Sagittarius, Gemini, Aquarius.\n**Least Compatible:** Cancer, Capricorn.",
    "horoscope": "A heartfelt compliment from a friend can brighten your entire day. You’ve built your life like a giving tree—offering shade to others while standing strong under the harsh sun yourself. Be mindful of your tendency to live in the moment and spend too freely on entertainment. This is also a good time to reconnect with old friends and revive past relationships. You may feel a noticeable emptiness due to the absence of love today. Avoid entering joint ventures or partnerships for now. After wrapping up household work, some Aries natives—especially homemakers—may enjoy relaxing with a movie or scrolling on their phones during free time. Marriage isn’t only about sharing a home; it’s also about giving your partner meaningful time.\n\nImportant job-related or personal tasks may need to be finished today to meet a deadline or honor a commitment. This could demand serious mental and physical energy, which may leave you feeling drained or stressed. Others may offer help, but it’s crucial you pace yourself. If you keep pushing while exhausted, the outcome may not be as good as you expect.",
    "yearly_forecast": "**2026 Overview:** A powerful year for inner reflection and professional growth. Planetary transits bring unexpected opportunities. Focus on self-analysis to prepare for big transformations.\n\n**Love:** Relationships deepen through shared activities. Passion is high, but communication is crucial to avoid misunderstandings.\n\n**Career:** Immense opportunities await. Networking and seizing unexpected offers will lead to success.\n\n**Health:** Prioritize sleep and stress management. Improved productivity depends on balancing your energy.\n\n**Education:** An above-average year. Success in competitive exams is likely. Students in tourism or media will thrive.\n\n**Family & Travel:** Domestic life may see mixed results; use logic to resolve conflicts. Long-distance travel brings mental peace."
  },
  {
    "name": "Taurus",
    "date": "Apr 20 - May 20",
    "icon": "♉",
    "element": "Earth",
    "ruling_planet": "Venus",
    "keywords": ["Reliable", "Patient", "Practical"],
    "traits": "Taurus is an earth sign represented by the bull...",
    "strengths": ["Reliable", "Patient", "Practical", "Devoted", "Responsible", "Stable"],
    "weaknesses": ["Stubborn", "Possessive", "Uncompromising"],
    "compatibility": "**Most Compatible:** Virgo, Capricorn, Cancer, Pisces.\n**Least Compatible:** Leo, Aquarius.",
    "horoscope": "This is a favorable day to lean into religious or spiritual interests. If you’ve been asking someone to repay money for a long time and they kept dodging it, luck may finally be on your side—they could return it unexpectedly today. Avoid discussing personal matters with casual acquaintances. You’re likely to strongly feel your partner’s presence even in their absence. Stay alert while dealing with influential people, as you may pick up a useful piece of advice. Someone from your past may reach out and make your day unforgettable. You and your spouse may also share an emotionally deep and romantic conversation today.\n\nA much-awaited vacation might finally be getting closer, Taurus. You may find yourself reading travel books, researching plans, and handling practical arrangements like calls, paperwork, and errands. You might also need to organize care for pets or plants while you’re away. Your excitement and enthusiasm are high, and you truly have something to look forward to—celebrate it and enjoy the moment!",
    "yearly_forecast": "**2026 Overview:** A spectacular year of stability and prosperity. Fresh opportunities in personal life and finances emerge.\n\n**Love:** Meaningful connections flourish. It's a time to build a partnership that feels like home, moving away from fleeting flings.\n\n**Career:** Financially prosperous! Jupiter boosts income and lifestyle, but caution against overspending is advised. Investments look promising.\n\n**Health:** Watch for digestive issues; proactive check-ups are key. Mental peace comes from a stable routine.\n\n**Education:** Academic performance peaks early in the year. High school students may relocate for better opportunities.\n\n**Family & Travel:** Family life requires patience due to dynamic shifts. Step out of your comfort zone—cultural trips are transformative."
  },
  {
    "name": "Gemini",
    "date": "May 21 - Jun 20",
    "icon": "♊",
    "element": "Air",
    "ruling_planet": "Mercury",
    "keywords": ["Adaptable", "Outgoing", "Intelligent"],
    "traits": "Have you ever been so busy that you wished you could clone yourself...",
    "strengths": ["Gentle", "Affectionate", "Curious", "Adaptable", "Ability to learn quickly"],
    "weaknesses": ["Nervous", "Inconsistent", "Indecisive"],
    "compatibility": "**Most Compatible:** Libra, Aquarius, Aries, Leo.\n**Least Compatible:** Virgo, Pisces.",
    "horoscope": "Your generosity can prove to be a hidden blessing today, as it may help you break free from negative traits like doubt, disloyalty, sadness, lack of faith, greed, attachment, ego, and jealousy. Established businesspeople should be extra cautious while making investments today. Spending time with friends in the evening will feel enjoyable and may even lead to some holiday planning. Your romantic feelings are likely to be returned warmly. It’s one of those rare days where work feels uplifting—colleagues will admire your effort, and even your boss may seem impressed by your progress. Business owners can also see profits today. Remember, nothing is truly out of reach when the will is strong. You may experience one of the best days of your married life today.\n\nToday could keep you quite busy, Gemini. Someone close might approach you for guidance on handling money or resources, especially if they trust your past experience. While it may take more time than you expected, you’ll enjoy being helpful. News from TV or newspapers could spark a fresh interest, motivating you to dive deeper and research something new.",
    "yearly_forecast": "**2026 Overview:** One of your luckiest years! Major developments in love and career await as planetary shifts spark independence.\n\n**Love:** New, meaningful relationships form early. Intellectual connection is vital—if the mind isn't engaged, the heart won't follow.\n\n**Career:** Major professional development is on the horizon. Your unique voice and ideas are your greatest assets.\n\n**Health:** Balance nervous energy with breathwork or yoga. Mental wellness is as important as physical fitness this year.\n\n**Education:** Excellent for competitive exams. Creativity is high, but managing time is essential for success.\n\n**Family & Travel:** Married life flourishes. Travel for work and exploration is favored—consider visiting Italy or Scotland to feed your curiosity."
  },
  {
    "name": "Cancer",
    "date": "Jun 21 - Jul 22",
    "icon": "♋",
    "element": "Water",
    "ruling_planet": "Moon",
    "keywords": ["Tenacious", "Imaginative", "Loyal"],
    "traits": "Cancer is a cardinal water sign...",
    "strengths": ["Tenacious", "Highly imaginative", "Loyal", "Emotional", "Sympathetic", "Persuasive"],
    "weaknesses": ["Moody", "Pessimistic", "Suspicious", "Manipulative", "Insecure"],
    "compatibility": "**Most Compatible:** Scorpio, Pisces, Taurus, Virgo.\n**Least Compatible:** Aries, Libra.",
    "horoscope": "Keep a check on your weight and avoid overeating today. New income opportunities may come through people you already know. Someone you live with might feel irritated by your unpredictable and overly casual behavior. Love-related emotions could keep you restless and disturb your sleep. Stay focused on your work and top priorities. After coming home, you may want to spend time on hobbies you enjoy—this will help calm your mind. However, differences in opinion may lead to an argument with your partner today.\n\nFamily-related social events could occupy much of your day, Cancer. These may involve outings to parks or recreational places. Even though you’ll enjoy the time, your mind might keep drifting to ongoing projects or responsibilities. Meaningful conversations with someone close can be mentally stimulating, leaving your thoughts racing by night. Make sure to get some physical movement so you can sleep more peacefully.",
    "yearly_forecast": "**2026 Overview:** A transformative year. Career struggles fade, leading to a lucky cycle when Jupiter enters your sign mid-year.\n\n**Love:** Early challenges lead to blossoming romance. Jupiter boosts joy in family and secure bonding.\n\n**Career:** A great period for finding work or launching projects. Trust your gut—your visibility and influence are increasing.\n\n**Health:** Vitality is good initially, but avoid overworking. Support your emotional well-being with nutrient-rich foods.\n\n**Education:** Self-discovery is key. Admissions to prestigious universities are possible, but discipline is required.\n\n**Family & Travel:** Focus on domestic peace early in the year. Travel for business expansion is likely."
  },
  {
    "name": "Leo",
    "date": "Jul 23 - Aug 22",
    "icon": "♌",
    "element": "Fire",
    "ruling_planet": "Sun",
    "keywords": ["Creative", "Passionate", "Generous"],
    "traits": "Roll out the red carpet, because Leo has arrived...",
    "strengths": ["Creative", "Passionate", "Generous", "Warm-hearted", "Cheerful", "Humorous"],
    "weaknesses": ["Arrogant", "Stubborn", "Self-centered", "Lazy", "Inflexible"],
    "compatibility": "**Most Compatible:** Aries, Sagittarius, Gemini, Libra.\n**Least Compatible:** Taurus, Scorpio.",
    "horoscope": "Elders should channel their extra energy into something positive to gain real benefits. Today, you’ll radiate positivity and step out with a calm and confident mindset—though your mood could be disturbed if a valuable item gets stolen or misplaced. Family matters may not feel as smooth as expected, and there’s a chance of tension or arguments at home, so try to keep your temper in control. Any lingering complaints or resentments in your relationship may dissolve, making the day feel surprisingly refreshing. Work can also become smoother if you simply greet someone who usually dislikes you—things may shift in your favor. Guidance from a spiritual leader or elder could be helpful today. You may also realize just how sweet and supportive your partner truly is.\n\nYour home might feel like a busy station today, with people constantly coming and going and plenty of activity happening around you. The phone may also keep ringing, adding to the chaos. You might worry about staying sane, but you’ll handle it fine. The only issue is that you may feel overly stimulated by night and struggle to sleep. A calming walk before bedtime will help.",
    "yearly_forecast": "**2026 Overview:** A fulfilled journey from slow starts to mid-year popularity. Prepare for personal reinvention.\n\n**Love:** Excellent shape early in the year. It's an ideal time to gain clarity and strengthen bonds with your partner.\n\n**Career:** Partnerships drive success. Teamwork is your golden ticket, so share the spotlight to achieve your big goals.\n\n**Health:** Protect your heart health with cardio. Seasonal minor issues may arise, but overall vitality is strong.\n\n**Education:** A year of development and leadership in potential student roles. Good results are expected.\n\n**Family & Travel:** Family feels secure and harmonious. You crave luxury with adventure—grand travel memories await."
  },
  {
    "name": "Virgo",
    "date": "Aug 23 - Sep 22",
    "icon": "♍",
    "element": "Earth",
    "ruling_planet": "Mercury",
    "keywords": ["Loyal", "Analytical", "Kind"],
    "traits": "Virgo is an earth sign historically represented by the goddess of wheat...",
    "strengths": ["Loyal", "Analytical", "Kind", "Hardworking", "Practical"],
    "weaknesses": ["Shyness", "Worry", "Overly critical of self and others", "All work and no play"],
    "compatibility": "**Most Compatible:** Taurus, Capricorn, Cancer, Scorpio.\n**Least Compatible:** Gemini, Sagittarius.",
    "horoscope": "You may experience persistent neck or back pain today, so don’t ignore it—especially if it comes with general weakness. Proper rest will be essential. There’s also a chance a colleague could steal or misplace something valuable, so keep a close eye on your belongings. Stay away from people who might pull you into unhealthy habits. Travel may strengthen romantic closeness. It’s a day to move carefully, so don’t present your ideas until you’re confident they’ll work. With your personality, too much social interaction can leave you drained—but today, you’re likely to get enough personal time even amidst the chaos. Your partner may do something unexpectedly wonderful that becomes a lasting memory.\n\nThis could turn into a hectic and fast-moving day, Virgo. You may be running errands, meeting multiple people, and spending a lot of time outside. A friend might tag along. Calls and planning for future events may also take up time, and someone could occupy you longer than expected just by chatting. Don’t rush—keep a steady pace and manage your energy well.",
    "yearly_forecast": "**2026 Overview:** Important lessons and big wins. Eclipses shake up relationships, challenging you to find joy in your inner world.\n\n**Love:** Commitment is tested. Whether single or attached, focus on relationships that support your personal growth and joy.\n\n**Career:** Saturn tests patience, but consistent effort pays off. Expect recognition for your efficiency in the second half.\n\n**Health:** Avoid overworking your digestive system. Schedule lighter meals and ensure you take mental breaks.\n\n**Education:** Hard work is needed after mid-year. Organization is your superpower and will lead to success.\n\n**Family & Travel:** Family life may need extra effort. You prefer organized trips—traditional festivals will delight you."
  },
  {
    "name": "Libra",
    "date": "Sep 23 - Oct 22",
    "icon": "♎",
    "element": "Air",
    "ruling_planet": "Venus",
    "keywords": ["Cooperative", "Diplomatic", "Gracious"],
    "traits": "Libra is an air sign represented by the scales...",
    "strengths": ["Cooperative", "Diplomatic", "Gracious", "Fair-minded", "Social"],
    "weaknesses": ["Indecisive", "Avoids confrontations", "Will carry a grudge", "Self-pity"],
    "compatibility": "**Most Compatible:** Gemini, Aquarius, Leo, Sagittarius.\n**Least Compatible:** Cancer, Capricorn.",
    "horoscope": "Stop smoking today—it will support your overall fitness and help you feel stronger. New income opportunities may appear through people you already know. Family matters could feel tense, and neglecting responsibilities at home may bring frustration from loved ones. Even with pending tasks, romance and social interactions may dominate your thoughts. Someone at work might try to interfere with your plans, so stay alert and observe what’s happening around you. Things may not move as smoothly as you want today. However, your spouse may express your importance with warm and meaningful words that touch you deeply.\n\nYou’re likely to feel energized and mentally sharp today, Libra, though a bit restless too. If possible, go for a workout, or at least a short walk. Much of your time may be spent handling challenging work that keeps your mind fully engaged. By evening, you might still feel keyed up—unwind by relaxing with something comforting and familiar.",
    "yearly_forecast": "**2026 Overview:** Big changes and new horizons! Adventure and travel call in the first half, followed by career expansion.\n\n**Love:** March turns up the heat. Drop illusions and communicate clearly. Boundaries will bring you closer to true intimacy.\n\n**Career:** A major level-up awaits. A new role aligning with your values is likely, especially after June.\n\n**Health:** Hydration is key for skin and kidney health. Recovery from past ailments looks very favorable.\n\n**Education:** Collaborative learning brings success. Early months are ideal for educational planning.\n\n**Family & Travel:** Family bonds strengthen after mid-year. Travel for growth is indicated."
  },
  {
    "name": "Scorpio",
    "date": "Oct 23 - Nov 21",
    "icon": "♏",
    "element": "Water",
    "ruling_planet": "Pluto",
    "keywords": ["Resourceful", "Brave", "Passionate"],
    "traits": "Scorpio is one of the most misunderstood signs...",
    "strengths": ["Resourceful", "Brave", "Passionate", "Stubborn", "A true friend"],
    "weaknesses": ["Distrusting", "Jealous", "Secretive", "Violent"],
    "compatibility": "**Most Compatible:** Cancer, Pisces, Virgo, Taurus.\n**Least Compatible:** Leo, Aquarius.",
    "horoscope": "From a health perspective, this is a strong and uplifting day. Your cheerful mood will work like a tonic, helping you feel confident and refreshed. Ignore anyone asking for short-term loans, as it may not be worth your time. You may be pleasantly surprised as your brother steps in to support you. Your success depends on working closely with others and keeping each other happy—remember, cooperation is the foundation of life. Your energy will remain high, especially since your beloved may bring you a lot of joy today. Business partners will feel enthusiastic about your new ideas and ventures. Travel may not bring instant results, but it will create a solid base for future gains. And for those who think marriage is only physical—today you’ll understand the meaning of real love.\n\nYou may pour a lot of physical and mental energy into creative or artistic work today, Scorpio. Your intuition is running strong, and you might sense what friends, loved ones, or children are feeling even before they speak. You may also absorb some of their stress, so take time to recharge. Hit the gym, then treat yourself to a concert or a game—you’ve earned some fun.",
    "yearly_forecast": "**2026 Overview:** A dynamic mix of opportunities. Cosmic shifts alter your course, bringing meaningful growth early in the year.\n\n**Love:** Singles might find someone special early. Existing relationships strengthen, with serious commitments like marriage possible.\n\n**Career:** Education and new skills are highlighted. It's a fantastic year to learn something that adds value to your toolkit.\n\n**Health:** Generally robust physical health. Minor ailments will be short-lived, so stay active.\n\n**Education:** Hard work pays off for exam takers. Travel for education may bring clarity.\n\n**Family & Travel:** Harmony prevails in the first half. Travel with friends or family is encouraged."
  },
  {
    "name": "Sagittarius",
    "date": "Nov 22 - Dec 21",
    "icon": "♐",
    "element": "Fire",
    "ruling_planet": "Jupiter",
    "keywords": ["Generous", "Idealistic", "Funny"],
    "traits": "Represented by the archer, Sagittarius is always on a quest...",
    "strengths": ["Generous", "Idealistic", "Great sense of humor"],
    "weaknesses": ["Promises more than can deliver", "Very impatient", "Will say anything no matter how undiplomatic"],
    "compatibility": "**Most Compatible:** Aries, Leo, Libra, Aquarius.\n**Least Compatible:** Virgo, Pisces.",
    "horoscope": "This is an excellent day to leave drinking behind. You must understand that alcohol is a serious enemy of your health and also weakens your efficiency. Today, you may take your family out for a get-together and end up spending generously on them. People will be drawn to you, and everyone may want your company—you’ll be happy to oblige. In love, use your judgment and think wisely. Your creativity and artistic talent will earn appreciation and may even bring unexpected rewards. You’ll have plenty of good ideas today, and the activities you choose can bring returns far beyond what you imagined. Some believe married life is only about conflict and physical attraction, but today feels peaceful and deeply harmonious.\n\nPending financial paperwork that you’ve been avoiding may need your attention today. Bills might need payment, deposits may need to be made, or new accounts could require setup. You may also spend time planning for the future. This could take up a good portion of your day, but you’ll still have time for shopping or handling important purchases. Friends may join you, making the day even more enjoyable.",
    "yearly_forecast": "**2026 Overview:** A supportive start with Jupiter aiding plans. You must balance your free spirit with Saturn's demand for discipline.\n\n**Love:** Professional life may distract initially, but Venus brings rewards later. Stability becomes more attractive than fleeting fun.\n\n**Career:** Mixed outcomes lead to success if you persist. Hard work is non-negotiable, but new avenues open after May.\n\n**Health:** Optimistic outlook, but watch for mental pressure. Meditation or yoga will help keep your fire balanced.\n\n**Education:** Unconventional fields call to you. Internships abroad will expand your horizons.\n\n**Family & Travel:** Mutual support strengthens family bonds. Your adventurous spirit will love international festivals."
  },
  {
    "name": "Capricorn",
    "date": "Dec 22 - Jan 19",
    "icon": "♑",
    "element": "Earth",
    "ruling_planet": "Saturn",
    "keywords": ["Responsible", "Disciplined", "Self-control"],
    "traits": "The last earth sign of the zodiac, Capricorn is represented by the sea goat...",
    "strengths": ["Responsible", "Disciplined", "Self-control", "Good managers"],
    "weaknesses": ["Know-it-all", "Unforgiving", "Condescending", "Expecting the worst"],
    "compatibility": "**Most Compatible:** Taurus, Virgo, Scorpio, Pisces.\n**Least Compatible:** Aries, Libra.",
    "horoscope": "Your health is likely to remain strong today, and because you’re feeling fit, you may even plan to play or spend time outdoors with friends. Financially, your position looks solid. With planets and nakshatras in your favor, you may come across several chances to earn money. Your charm and personality will help you make a few new connections. Love feels limitless today—you’ve heard such lines before, but now you may truly experience it. Interestingly, the most irritating teammate at work might suddenly surprise you with intelligence or depth. Guidance from a spiritual figure or elder could prove helpful. And while love after marriage often sounds difficult, you may feel it flowing naturally throughout your day.\n\nYour energy levels—both mental and physical—will be high today, Capricorn, and you might feel restless during the morning. This could lead you to spend much of the afternoon and evening outside, shopping, visiting people, or attending lectures/classes. Engaging conversations are likely. At some point, you might find yourself appreciating a garden or park. Just don’t overload your schedule—enjoy the day at a comfortable pace.",
    "yearly_forecast": "**2026 Overview:** Big transitions in every area. The pressure gives way to evolution and financial refinement.\n\n**Love:** Social expansion brings joy. Existing partnerships flourish, and singles may find stable, long-term prospects.\n\n**Career:** Financial growth is the focus. Saturn helps you solidify plans, and collaboration becomes your path to the top.\n\n**Health:** Strengthen your bones with Vitamin D and resistance training to match your strong ambition.\n\n**Education:** Consistent success. Good for long-term goals and certifications due to strong concentration.\n\n**Family & Travel:** Good news from maternal relatives is likely. You prefer structured trips—relaxing or hiking adventures fit your style."
  },
  {
    "name": "Aquarius",
    "date": "Jan 20 - Feb 18",
    "icon": "♒",
    "element": "Air",
    "ruling_planet": "Uranus",
    "keywords": ["Progressive", "Original", "Independent"],
    "traits": "Despite the \"aqua\" in its name, Aquarius is actually the last air sign...",
    "strengths": ["Progressive", "Original", "Independent", "Humanitarian"],
    "weaknesses": ["Runs from emotional expression", "Temperamental", "Uncompromising", "Aloof"],
    "compatibility": "**Most Compatible:** Gemini, Libra, Aries, Sagittarius.\n**Least Compatible:** Taurus, Scorpio.",
    "horoscope": "Avoid heavy and high-calorie foods today so you can stay light, active, and healthy. Ignore those who approach you for business credit, as it may create unnecessary complications. An evening movie or a dinner with your spouse can bring a relaxed and joyful vibe. Your partner’s eyes won’t hide what they feel—today, they may communicate something truly special without words. New ventures may seem tempting and could offer good returns. In your free time, you might enjoy watching a web series on your phone. Your spouse may also surprise you with a thoughtful or special purchase.\n\nYour imagination and creative inspiration are running high today, Aquarius. If you’ve been thinking of starting an artistic project, this is the perfect day to begin. You’ll also feel more intuitive than usual, and you may pick up on the emotions and needs of others—even strangers. Your higher awareness feels very close to your conscious mind right now, so use it wisely and make the most of this powerful mental clarity.",
    "yearly_forecast": "**2026 Overview:** A year to shine! Significant growth in career and finances. The first half is for planning; the second brings breakthroughs.\n\n**Love:** Communication is your lifeline. Long-distance or online connections could surprise you. Patience is key in matters of the heart.\n\n**Career:** Saturn gives you control over your path, while Jupiter offers expansion. Property investments and financial gains look favorable.\n\n**Health:** Improve circulation with movement breaks. Consistent activity keeps your innovative mind sharp.\n\n**Education:** Excellent prospects for research and higher education, especially after May.\n\n**Family & Travel:** Family tension fades after mid-year. Professional changes in spring might inspire travel."
  },
  {
    "name": "Pisces",
    "date": "Feb 19 - Mar 20",
    "icon": "♓",
    "element": "Water",
    "ruling_planet": "Neptune",
    "keywords": ["Compassionate", "Artistic", "Intuitive"],
    "traits": "Pisces, a water sign, is the last constellation of the zodiac...",
    "strengths": ["Compassionate", "Artistic", "Intuitive", "Gentle", "Wise", "Musical"],
    "weaknesses": ["Fearful", "Overly trusting", "Sad", "Desire to escape reality"],
    "compatibility": "**Most Compatible:** Cancer, Scorpio, Taurus, Capricorn.\n**Least Compatible:** Gemini, Sagittarius.",
    "horoscope": "Even with a hectic schedule, your health should remain strong today. You should avoid spending money on alcohol or cigarettes—doing so won’t just harm your health, it could also weaken your finances. Someone around you may overreact to money-related matters, creating slight tension at home. Romantic opportunities may appear, but they’re likely to be brief. Avoid mixing business with pleasure today. By the end of the day, you’ll want to spend time with family, but an argument with someone close could spoil your mood if you’re not careful. Still, today may also remind you how fortunate you are to have such a wonderful life partner.\n\nA group you’re connected with may ask you to handle a few tasks, such as making calls, running errands, or managing multiple small responsibilities. Your energy and enthusiasm are high, making this a great chance to prove your value and efficiency. Just be careful not to take on too much—you won’t help anyone if you end up exhausting yourself.",
    "yearly_forecast": "**2026 Overview:** Introspection and rebirth. As Saturn prepares to leave, you emerge more grounded, mature, and spiritually connected.\n\n**Love:** Relationships take on a deeper meaning. You seek soul connections, and casual dating loses its appeal.\n\n**Career:** Strategic planning wins the race. It's a year to balance your dreams with reality. Artistic and healing professions continue to be favored.\n\n**Health:** Support your immunity with herbal teas and adaptogens. Your sensitive nature needs extra care during this transition.\n\n**Education:** Success in creative fields. Studying abroad or travel-related subjects is highly favored.\n\n**Family & Travel:** Manage minor family tensions with communication. Travel for relaxation is key—beaches call to your water spirit."
  }
]
